name: Deploy Fullstack App
on:
  push:
    branches:
      - main
jobs:
  deploy-backend-prod:
    name: Deploy Backend
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    environment: prod
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1
        env:
          DEPLOY_WORKSPACE_DIRNAME: ${{ secrets.DEPLOY_WORKSPACE_DIRNAME }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${DEPLOY_WORKSPACE_DIRNAME}
            git pull origin main
            NCS_ENV=prod bash script/deploy_fullstack_app.sh
          envs: DEPLOY_WORKSPACE_DIRNAME
  deploy-frontend-prod:
    name: Deploy Frontend
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    needs: deploy-backend-prod
    environment: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Deploy Frontend
        env:
          DOTENV_PRIVATE_KEY_ENV: ${{ secrets.DOTENV_PRIVATE_KEY_ENV }}
          NCS_ENV: ${{ vars.NCS_ENV }}
          TZ: ${{ vars.TZ }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.46.0
          command: |
            pages download config nishikata-coast-story
            pages deploy --project-name nishikata-coast-story
