name: Deploy Fullstack App
on:
  push:
    branches:
      - main
jobs:
  deploy-backend-app-prod:
    name: Deploy Backend App
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    environment: Production
    steps:
      - name: Deploy Backend App
        uses: appleboy/ssh-action@v1
        env:
          DEPLOY_WORKSPACE_DIRNAME: ${{ secrets.DEPLOY_WORKSPACE_DIRNAME }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${DEPLOY_WORKSPACE_DIRNAME}
            git pull origin main
            NCS_ENV=prod bash script/deploy_fullstack_app.sh
          envs: DEPLOY_WORKSPACE_DIRNAME
  deploy-frontend-app-prod:
    name: Deploy Frontend App
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    needs: deploy-backend-app-prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Build Frontend App
        run: |
          vercel pull --yes --environment production --token ${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Frontend App
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
