name: Deploy Fullstack App
on:
  push:
    branches:
      - main
jobs:
  deploy-backend-app-prod:
    name: Deploy Backend App
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    environment: prod
    steps:
      - name: Deploy Backend App
        uses: appleboy/ssh-action@v1
        env:
          DEPLOY_WORKSPACE_DIRNAME: ${{ secrets.DEPLOY_WORKSPACE_DIRNAME }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${DEPLOY_WORKSPACE_DIRNAME}
            git pull origin main
            NCS_ENV=prod bash script/deploy_fullstack_app.sh
          envs: DEPLOY_WORKSPACE_DIRNAME
  deploy-frontend-app-prod:
    name: Deploy Frontend App
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    needs: deploy-backend-app-prod
    environment: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
      - name: Install Dependencies
        run: npm install -g @dotenvx/dotenvx && npm install
        working-directory: frontend/web
      - name: Build Frontend App
        env:
          DOTENV_PRIVATE_KEY_ENV: ${{ secrets.DOTENV_PRIVATE_KEY_ENV }}
          NCS_ENV: ${{ vars.NCS_ENV }}
        run: npm run nuxt:build -- --preset=cloudflare_pages
        working-directory: frontend/web
      - name: Deploy Frontend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.46.0
          command: pages deploy frontend/web/dist --project-name nishikata-coast-story
