name: QC DB
on: pull_request
jobs:
  qc-db:
    name: QC DB
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install Dependencies
        run: npm install -g @dotenvx/dotenvx && npm install && npm run prisma:generate
        working-directory: backend/db
      - name: Run ESLint
        run: npm run eslint
        working-directory: backend/db
      - name: Run TypeCheck
        run: npm run tsc:check
        working-directory: backend/db
