name: QC Web
on: pull_request
jobs:
  qc-web:
    name: QC Web
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - name: Install Dependencies
        run: npm install -g @dotenvx/dotenvx && npm install && npm run prisma:generate
        working-directory: frontend/web
      - name: Run ESLint
        run: npm run eslint:lint
        working-directory: frontend/web
      - name: Run TypeCheck
        run: npm run typescript:lint
        working-directory: frontend/web
