name: Scan Code (CodeQL)
on: pull_request
jobs:
  scan-code:
    name: Scan Code
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: actions, javascript-typescript
          queries: security-and-quality
      - name: Run CodeQL
        uses: github/codeql-action/init@v4

name: Scan Code (OSV-Scanner)
on: pull_request
jobs:
  scan-code:
    name: Scan Code
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      security-events: write
      contents: read
    steps:
      - name: Run OSV-Scanner
        uses: google/osv-scanner-action@v2.3.0
